name: battle

on:
  push:
  pull_request:
  repository_dispatch:

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  battle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - uses: gradle/gradle-build-action@v2
      - env:
          BATTLE_SESSIONS: ${{ github.event.client_payload.sessions }}
        run: ./gradlew runBattles


      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/runBattles/TEST-*.xml'

      - name: Deploy battle results
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'bnorm/jarvis' }}
        with:
          publish_dir: ./jarvis/build/battles
          destination_dir: ./battes/${{ github.sha }}/
